version: "3"
services:
  wordpress:
    image: wordpress
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "passwd"
      WORDPRESS_DB_NAME: wordpress 
    networks:
      wordp:
        ipv4_address: "192.168.50.14"
  mysql:
    image: "mysql:latest"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "passwd"
    volumes:
      - ./mysql:/var/lib/mysql  # Corrected indentation
    networks:
      wordp:
        ipv4_address: "192.168.50.15"
networks:
  wordp:
    ipam:
      driver: default
      config:
        - subnet: "192.168.50.0/24"

